spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 459773521146-ar955t0h7p4mdo3de4n1f8d4tb8a2fpc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 766540228067011
            client-secret: 55e97fae73dfa635a3fb5f262d251ef8
            scope:
              - email
              - public_profile

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800



